### ISSUE TITLE
Compiling for Linux

### ISSUE THREAD

**Issue by osxster** [castvoid/xserve-frontpanel#8]
I was curious if there is a way to compile this for Linux.  I'd like to use this on an ESXi host, however ESXi doesn't have a compiler and thus I am trying to get this to compile on CentOS or BSD instead to see if it can be copied over to ESXi.

Below I am trying with CentOS 8.1, I am able to get this to get a lot of the way through, but it fails a trying to find mach/mach_host.h.  See below:

[root@localhost xserve-frontpanel-master]# cmake . && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/HOME/xserve-frontpanel-master
[ 33%] Building C object CMakeFiles/hwmond.dir/cpu_usage.c.o
In file included from /home/HOME/xserve-frontpanel-master/cpu_usage.c:1:
/home/HOME/xserve-frontpanel-master/cpu_usage.h:3:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
 #import <stdlib.h>
  ^~~~~~
/home/HOME/xserve-frontpanel-master/cpu_usage.c:5:10: fatal error: mach/mach_host.h: No such file or directory
 #include <mach/mach_host.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hwmond.dir/build.make:76: CMakeFiles/hwmond.dir/cpu_usage.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/hwmond.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

It is failing because it is looking for Mach Kernel files which is the Kernel used by MacOS.  Is there a way to update this to use Kernel files from Linux?  I'd love go to see this work, any help would be greatly appreciated.

**Comment by ryandesign** [comment]
ESXi can run some Linux ELF binaries but ESXi is not Linux. (ESX was, but ESXi isn't.) I already filed #4 for compiling for ESXi so this new ticket could be about compiling for Linux per your title.

All the Mach-related variables and functions in the code are specific to operating systems like macOS/Darwin that use the Mach microkernel and will need to be made conditional on that (i.e. `#ifdef __MACH__`). Alternative implementations will need to be created for any other operating systems.

Everything I've found about how to get CPU core usage on Linux says to parse the first few lines of the contents of /proc/stat, for example [this programming question](https://unix.stackexchange.com/questions/21543/get-cpu-utilization-stats-from-c-program) and also the source code of [unixtop](https://sourceforge.net/projects/unixtop/). I was hoping there would be an actual operating system function that you would call to get this information like there is in Mach, but apparently there is not.

ESXi has /proc but does not have /proc/stat so this method won't work there. I'll discuss what will work on ESXi in #4.

**Comment by ryandesign** [comment]
> I was hoping there would be an actual operating system function that you would call to get this information like there is in Mach

Ah, of course the function in question can be found by looking at the source code for the `show_stat` function in the Linux kernel. Perhaps running just the functions to get the specific CPU info we need is more efficient than having the kernel generate the entire page of info and then parsing it.

I won't link to that code because of the licensing quandry: like the rest of Linux that function is licensed GPL, while this project is licensed MIT, so we could not copy parts of their code into this project without it becoming a derivative work and transforming it into a GPL project. I've looked at the `show_stat` code so I'm tainted and couldn't write the new code. But I could describe what needs to be done, and mention which kernel header contains the function definitions and structs that would need to be used, and someone else could create a clean room implementation from my description.

We could just go with parsing /proc/stat for now and leave calling the kernel functions directly as an optimization for later.

**Comment by ryandesign** [comment]
I've installed Linux, figured out how to use X11 forwarding, figured out how to add some code to CMakeLists.txt, separated the Mach-specific code into another file, made a different file for Linux which just uses random numbers so far, figured out how to configure udev to allow write access to the front panel controller, and now I'm stuck at:

```
$ build/hwmond
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.003232] [00000e2b] libusb: debug [libusb_get_device_list]
[ 0.003267] [00000e2b] libusb: debug [libusb_get_device_descriptor]
[ 0.003276] [00000e2b] libusb: debug [libusb_get_device_descriptor]
[ 0.003284] [00000e2b] libusb: debug [libusb_open] open 2.5
[ 0.003320] [00000e2b] libusb: debug [usbi_add_pollfd] add fd 9 events 4
[ 0.003332] [00000e2b] libusb: debug [libusb_set_configuration] configuration 0
[ 0.474419] [00000e2b] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.474514] [00000e2b] libusb: debug [libusb_claim_interface] interface 0
Couldn't claim interface: -5
[ 0.474560] [00000e2b] libusb: debug [libusb_close]
[ 0.474567] [00000e2b] libusb: debug [usbi_remove_pollfd] remove fd 9
```

`-5` is `LIBUSB_ERROR_NOT_FOUND` (and I'll fix the code to use `libusb_error_name` so that it prints the name instead of the number). [API documentation](http://libusb.sourceforge.net/api-1.0/group__libusb__dev.html#gaee5076addf5de77c7962138397fd5b1a) says this happens when the interface does not exist, but it seems like the preceding code has already verified that it does exist, and of course it works as is on macOS.

I found a suggestion that there could be a kernel driver attached to the device, and that one should use `libusb_kernel_driver_active` to check and if so call `libusb_detach_kernel_driver` to detach it, and I wrote code to do that, but that didn't change it. I'll investigate more tomorrow.

**Comment by newhacker1746** [comment]
Hi! I tried to compile for Linux earlier but failed and didn't think about filing an issue. I have an Xserve2,1 on 5.11.0 so I am also happy to test (and be in the loop)

One thing about the GPL "taint": couldn't we do an FFmpeg and simply warn that compiling with the GPL link makes the binary nondistributable or under the GPL license or something like that? Simply adding an #ifdef LINUX does not taint builds unless it actually is compiled for Linux, and even then it does not taint the whole project, merely the binary-- Or so I thought?

**Comment by ryandesign** [comment]
It's not my project of course but I personally favor non-GNU licenses and wouldn't want to introduce the licensing complications at this point. If the owner of the project wants to change its license to GPL that's up to them. But I think we'll be fine to just read /proc/stat for Linux to start with and can optimize later if needed. I'm not to the point of writing that code yet; I have some more elementary things to become accustomed to on Linux first, since I'm a Mac guy and haven't used Linux much.

**Comment by ryandesign** [comment]
I now have random LEDs working in Ubuntu Server 20.04 and ESXi 6.0.0. Next step will be to implement real CPU activity data capturing for Linux and then for ESXi.

**Comment by lilynet336** [comment]
Don't know if this project is still alive, but I recently got CentOS Linux installed on my old Xserve and I am having trouble getting this to work. I installed libusb and ran `cmake .`, but `make` fails with a few errors. I was able to get it working fine on macOS 10.13 before, but it seems to be finicky on CentOS. I have tried both this repo and the one forked by @ryandesign, both to no avail. I am not knowledgable with C. Does anyone here have any thoughts? Thank you.

The make output is:
```
[ 25%] Building C object CMakeFiles/hwmond.dir/cpu_usage.c.o
[ 50%] Linking C executable hwmond
CMakeFiles/hwmond.dir/cpu_usage.c.o: In function `get_usage_by_core':
cpu_usage.c:(.text+0x20): undefined reference to `fetch_ticks_by_core'
CMakeFiles/hwmond.dir/cpu_usage.c.o: In function `cpu_usage_setup':
cpu_usage.c:(.text+0x325): undefined reference to `get_num_packages'
cpu_usage.c:(.text+0x343): undefined reference to `fetch_ticks_by_core'
collect2: error: ld returned 1 exit status
make[2]: *** [hwmond] Error 1
make[1]: *** [CMakeFiles/hwmond.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nano11b** [comment]
> Don't know if this project is still alive, but I recently got CentOS Linux installed on my old Xserve and I am having trouble getting this to work. I installed libusb and ran `cmake .`, but `make` fails with a few errors. I was able to get it working fine on macOS 10.13 before, but it seems to be finicky on CentOS. I have tried both this repo and the one forked by [@ryandesign](https://github.com/ryandesign), both to no avail. I am not knowledgable with C. Does anyone here have any thoughts? Thank you.
> 
> The make output is:
> 
> ```
> [ 25%] Building C object CMakeFiles/hwmond.dir/cpu_usage.c.o
> [ 50%] Linking C executable hwmond
> CMakeFiles/hwmond.dir/cpu_usage.c.o: In function `get_usage_by_core':
> cpu_usage.c:(.text+0x20): undefined reference to `fetch_ticks_by_core'
> CMakeFiles/hwmond.dir/cpu_usage.c.o: In function `cpu_usage_setup':
> cpu_usage.c:(.text+0x325): undefined reference to `get_num_packages'
> cpu_usage.c:(.text+0x343): undefined reference to `fetch_ticks_by_core'
> collect2: error: ld returned 1 exit status
> make[2]: *** [hwmond] Error 1
> make[1]: *** [CMakeFiles/hwmond.dir/all] Error 2
> make: *** [all] Error 2
> ```

I got a similar error so I ended up replacing cpu_usage.c with my own. Make sure you backup the original file.
```bash
#include <stdio.h>

float get_cpu_usage() {
    static long prev_idle=0, prev_total=0;
    long user,nice,system,idle,iowait,irq,softirq;
    long total,diff_idle,diff_total;

    FILE *fp=fopen("/proc/stat","r");
    if(!fp) return 0;

    fscanf(fp,"cpu %ld %ld %ld %ld %ld %ld %ld",
           &user,&nice,&system,&idle,
           &iowait,&irq,&softirq);

    fclose(fp);

    total=user+nice+system+idle+iowait+irq+softirq;

    diff_idle=idle-prev_idle;
    diff_total=total-prev_total;

    prev_idle=idle;
    prev_total=total;

    if(diff_total==0) return 0;

    return 100.0 * (1.0 - ((float)diff_idle / diff_total));
}
```

Also you might find these useful:
- If no build tools you'll need ``apt install build-essential make cmake``
- Added ``apt install libusb-dev libusb-1.0-0 libusb-1.0-0-dev``
- Changed original to ``cmake . -DLINUX=O && make``

**Comment by mav2287** [comment]
Knowing that this was always a pet project for the original Dev that created this, I recently built a direct replacement to the original hwmond service that used to run these lights on the Xserves. If you just looking for something you can install without having to compile that works for Linux/ESXi you can find it here https://github.com/mav2287/hwmond in addition to the LED and CPU lights it also has the added benefit that it populates all of the information for server monitor that the original service used to do within macOS. I use it on my Xserves so I plan to continue maintaining it as long as they keep running.
